config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :attendees
  devise_for :users
  root to: 'home#index'
  resources :workshops, only: %i[index new create show edit index update]

  resources :enrollments, only: %i[destroy] do
    post :waiting_list_create, to: 'enrollments#waiting_list_create', as: 'waiting_list', on: :collection
  end
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/attendee.rb
# frozen_string_literal: true

class Attendee < ApplicationRecord
  has_many :enrollments
  
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :name, presence: true
end

app/models/enrollment.rb
# frozen_string_literal: true

class Enrollment < ApplicationRecord
  belongs_to :workshop
  belongs_to :attendee

  validates :status, presence: true
  validate :already_enrolled, :already_enrolled_waiting_list

  enum status: { enrolled: 0, waiting_list: 1 }

  def already_enrolled
    return if self.class.where(workshop: workshop, attendee: attendee, status: :enrolled).empty?

    errors.add(:base, I18n.t('enrollments.flash.error.already_enrolled', workshop_name: workshop.name))
  end

  def already_enrolled_waiting_list
    return if self.class.where(workshop: workshop, attendee: attendee, status: :waiting_list).empty?

    errors.add(:base, I18n.t('enrollments.flash.error.already_enrolled_waiting_list', workshop_name: workshop.name))
  end
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/workshop.rb
# frozen_string_literal: true

class Workshop < ApplicationRecord
  has_many :enrollments, dependent: :restrict_with_exception

  STATUSES = %i[draft active inactive].freeze

  validates :name, :short_description, :full_description, :duration,
            :attendees, :workshop_date, :start_time, :status, presence: true

  scope :future, -> { where('workshop_date > ?', Time.zone.now) }

  enum status: STATUSES

  def full?
    enrollments.size >= attendees
  end

  def enrolled?(attendee)
    enrollments.where(attendee: attendee, status: :enrolled).any?
  end

  def waiting_list_enroll(attendee)
    return nil unless full?

    enrollments.create!(attendee: attendee, status: :waiting_list)
  end

  def disenroll(attendee)
    enrollments.find_by(attendee: attendee, status: :enrolled)&.destroy
  end
end

app/models/workshop_content.rb
# frozen_string_literal: true

class WorkshopContent < ApplicationRecord
  belongs_to :workshop
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  before_action :attendee_permitted_parameters, if: :devise_controller?

  protected

  def attendee_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end
end

app/controllers/enrollments_controller.rb
# frozen_string_literal: true

class EnrollmentsController < ApplicationController
  before_action :authenticate_attendee!

  def waiting_list_create
    workshop = Workshop.find(params[:workshop_id])

    workshop.waiting_list_enroll(current_attendee)

    redirect_to(workshop, flash: { success: I18n.t('enrollments.flash.success.waiting_list_enroll',
                                                   workshop_name: workshop.name) })
  rescue StandardError => e
    redirect_to(workshop, flash: { error: e.message })
  end

  def destroy
    enrollment = Enrollment.find(params[:enrollment_id])
    workshop = enrollment.workshop
    attendee = enrollment.attendee

    # check if current attendee is the enrollment's attendee 
    enrollment.destroy if attendee == current_attendee

    redirect_to(workshop, flash: { success: I18n.t('enrollments.flash.success.unenroll_attendee',
                                                   workshop_name: workshop.name) })
    rescue StandardError => e
      redirect_to(workshop, flash: { error: e.message })
  end
end

app/controllers/home_controller.rb
# frozen_string_literal: true

class HomeController < ApplicationController
  def index; end
end

app/controllers/workshops_controller.rb
# frozen_string_literal: true

class WorkshopsController < ApplicationController
  before_action :authenticate_user!, except: [:show, :index]
  # INDEX
  def index
    @workshops = Workshop.future
  end

  # GET
  def new; end

  # POST
  def create
    workshop = Workshop.new(workshop_params)
    workshop.save

    # direciona para o show
    redirect_to workshop, notice: 'Workshop registrado com sucesso'
  end

  # GET /workshops/:id
  def show
    @workshop = Workshop.find(params[:id])
    @enrollment = Enrollment.find_by(attendee: current_attendee, workshop: @workshop)

    return if can_view_workshop?(@workshop.draft?)

    redirect_to root_path, notice: I18n.t('workshops.notices.show.draft')
  end

  def edit
    @workshop = Workshop.find(params[:id])
  end

  def update
    workshop = Workshop.find(params[:id])
    workshop.update!(workshop_params)
    redirect_to edit_workshop_path(workshop),
                notice: I18n.t('workshops.notices.edit.success',
                               name: workshop.name)
  end

  private

  def workshop_params
    # Strong Parameters
    params.require(:workshop).permit(:name, :short_description,
                                     :full_description, :duration,
                                     :attendees, :workshop_date,
                                     :start_time, :status)
  end

  def can_view_workshop?(draft_workshop)
    return true if user_signed_in?

    attendee_signed_in? && !draft_workshop ? true : false
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/views/attendees/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/attendees/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end %>
<% end %>

app/views/home/index.html.erb
<% if user_signed_in? %>
  <%= link_to t(".register_workshops"), new_workshop_path %>
  <%= link_to t(".list_workshops"), workshops_path %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Workshops</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% flash.each do |name, msg| %>
      <%= content_tag :div, msg, class: name %>
    <% end %>
    <%= yield %>
  </body>
</html>

app/views/users/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end %>
<% end %>

app/views/workshops/_form.html.erb
<%= form_with(model: workshop, local: true) do |f| %>
  <div>
    <%= f.label :name, 'Nome' %>
    <%= f.text_field :name  %>
  </div>
  <div>
    <%= f.label :short_description, 'Descrição Curta' %>
    <%= f.text_field :short_description %>
  </div>
  <div>
    <%= f.label :full_description, 'Descrição Completa' %>
    <%= f.text_field :full_description %>
  </div>
  <div>
    <%= f.label :attendees, 'Capacidade Máxima' %>
    <%= f.text_field :attendees %>
  </div>
  <div>
    <%= f.label :workshop_date, 'Data' %>
    <%= f.date_field :workshop_date %>
  </div>
  <div>
    <%= f.label :start_time, 'Hora' %>
    <%= f.time_field :start_time %>
  </div>
  <div>
    <%= f.label :duration, 'Duração' %>
    <%= f.number_field :duration %>
  </div>
  <%= yield f %>
  <%= f.submit form_action %>
<% end %>

app/views/workshops/edit.html.erb
<h1><%= t('.title') %></h1>

<%= render "form", workshop: @workshop, form_action: t(".submit") do |f| %>
  <div>
    <%= f.label :status %>
    <%= f.select :status, Workshop::STATUSES.collect {|status| [I18n.t("workshops.status.#{status}"), status] }  %>
  </div>
<% end %>

app/views/workshops/index.html.erb
<h1><%= t(".title") %></h1>

<% if @workshops.any? %>

  <% @workshops.each do |workshop| %>
    <h1><%= workshop.name %></h1>
    <dl>
      <dt><%= I18n.t 'activerecord.attributes.workshop.short_description' %></dt>
      <dd><%= workshop.short_description %></dd>
      <dt><%= I18n.t 'activerecord.attributes.workshop.duration' %></dt>
      <dd><%= workshop.duration %> minutos</dd>
      <dt><%= I18n.t 'activerecord.attributes.workshop.workshop_date' %></dt>
      <dd><%= I18n.localize workshop.workshop_date %></dd>
      <dt><%= I18n.t 'activerecord.attributes.workshop.start_time' %></dt>
      <dd><%= l workshop.start_time, format: :short %></dd>
      <dt><%= I18n.t 'activerecord.attributes.workshop.attendees' %></dt>
      <dd><%= workshop.attendees %></dd>
      <dt><%= t(".table.action") %></dt>
      <dd><%= link_to t('.edit'), edit_workshop_path(workshop) %></dd>
    </dl>
  <% end %>

<% else %>
  <p><%= t(".table.empty") %></p>
<% end %>

app/views/workshops/new.html.erb
<h1><%= t(".title") %></h1>

<%= render "form", workshop: Workshop.new, form_action: t(".submit") %>

app/views/workshops/show.html.erb
<h1><%= @workshop.name %></h1>
<dl>
  <dt><%= t('.short_description') %></dt>
  <dd><%= @workshop.short_description %></dd>
  <dt><%= t('.full_description') %></dt>
  <dd><%= @workshop.full_description %></dd>
  <dt><%= t('.duration') %></dt>
  <dd><%= @workshop.duration %> minutos</dd>
  <dt><%= t('.start_date') %></dt>
  <dd><%= I18n.localize @workshop.workshop_date %></dd>
  <dt><%= t('.start_time') %></dt>
  <dd><%= l @workshop.start_time, format: :short %></dd>
  <% if @workshop.full? %>
    <dt><%= t('.waiting_list') %></td>
    <dd><%= link_to(t('.waiting_list_link'), waiting_list_enrollments_path(workshop_id: @workshop.id), method: :post) %></dd>
  <% end %>

  <%# Show unenroll link if attenddee is enrolled on workshop %>
  <% if @enrollment %>
    <dt><%= t('.enrollment') %></td>
    <dd><%= link_to('Cancelar inscrição', enrollment_path(enrollment_id: @enrollment.id), method: :delete) %></dd>
  <% end %>

</dl>